/// WHEN WE DEAL WITH CONSTANT OBJECTS , WE CANT CHANGE THEIR PROPERTIES 
/// EVEN THE COMPILER DOESNT ALLOW US TO CALL FUNCTIONS AS IT MIGHT THINK THT ITS VAUE IS CHANGING IN THE FUCNTON .
//// WE NEED TO MARK FUCNTIONS WHICH WE HAVE MADE TO DEAL WITH CONSTANT OBJECTS ,CONSTANT

//CONSIDER IT A FUNCTION IN CLASS 
void get_value() const  ///// CONSTANT FUCNTIO
{
    return 
}